// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Application(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Hello ReScript!"));
}

var make = Application;

export {
  make ,
  
}
/* react Not a pure module */
