// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Application from "./Application.bs.js";

var app = document.querySelector("#app");

if (!(app == null)) {
  ReactDom.render(React.createElement(Application.make, {}), app);
}

export {
  
}
/* app Not a pure module */
